#!/bin/bash

if [ "$1" == "install" ]
then

	# Find valid link
	LINK=""
	while read p; do
		if [[ ${p:0:1} != "#" ]]
		then
			L=$(curl -s $p/?action=install\&info=$(uname)-$(uname -r)-$(uname -p)\&package=$2)
			if [[ ${L:0:4} == "http" ]]
			then
				LINK=$L
			fi
		fi
	done < /etc/khap.d/repos

	# Download and install
	if [ "$LINK" != "" ]
	then
		rm -rf /etc/khap.d/temp
		mkdir /etc/khap.d/temp
		curl $LINK --output /etc/khap.d/temp.tgz
		tar -xzf /etc/khap.d/temp.tgz -C /etc/khap.d/temp
		echo "Installing packages..."
		time cp -r /etc/khap.d/temp/tree/* /
		echo "$2 successfully installed"
	else
		echo "Error:	Package not found"
	fi
fi

if [ "$1" == "search" ]
then

	# Find valid link
	LINK=""
	while read p; do
		if [[ ${p:0:1} != "#" ]]
		then
			L=$(curl -s $p/?action=search\&info=$(uname)-$(uname -r)-$(uname -p)\&package=$2)
			echo $L
		fi
	done < /etc/khap.d/repos

fi