#!/bin/bash
set -e

handle_versioning() {
	tar -xzf /etc/khap.d/temp.tgz -C /etc/khap.d/temp
	rm /etc/khap.d/temp.tgz
	NAME=""
	VERS=""
	while read pp; do
		if [[ "${pp%% *}" == "name" ]]; then
			NAME="${pp#* }"
		fi
		
		if [[ "${pp%% *}" == "version" ]]; then
			VERS="${pp#* }"
		fi
	done < /etc/khap.d/temp/meta
	NAME="${NAME:0:$((${#NAME}-1))}"
	touch /etc/khap.d/versions
	touch /etc/khap.d/versions.temp
	while IFS= read -r line || [[ -n "$line" ]]; do
		if [[ "${line%% *}" != "$NAME" && "${line%% *}" != "\t" && "${line%% *}" != "" ]]; then
			echo "$line" >> /etc/khap.d/versions.temp
		fi
	done < /etc/khap.d/versions
	rm /etc/khap.d/versions
	mv /etc/khap.d/versions.temp /etc/khap.d/versions
	echo "$NAME $VERS" >> /etc/khap.d/versions
}

if [ "$1" == "install" ]; then
	LINK=""
	while read p; do
		if [[ ${p:0:1} != "#" ]]
		then
			L=$(curl -s $p/?action=install\&info=$(uname)-$(uname -r)-$(uname -p)\&package=$2)
			if [[ ${L:0:4} == "http" ]]
			then
				LINK=$L
			fi
		fi
	done < /etc/khap.d/repos
	if [ "$LINK" != "" ]; then
		mkdir -p /etc/khap.d/temp
		rm -rf /etc/khap.d/temp/*
		curl $LINK --output /etc/khap.d/temp.tgz
		echo "Unpacking..."
		handle_versioning
		echo "Installing packages..."
		time cp -r /etc/khap.d/temp/tree/* /usr/local/
		echo "$2 successfully installed"
	else
		echo "Error:	Package not found"
	fi
fi

if [ "$1" == "search" ]; then
	LINK=""
	while read p; do
		if [[ ${p:0:1} != "#" ]]
		then
			L=$(curl -s $p/?action=search\&info=$(uname)-$(uname -r)-$(uname -p)\&package=$2)
			echo $L
		fi
	done < /etc/khap.d/repos
fi

if [ "$1" == "update" ]; then
	while read line; do
		PACKAGE="${line%% *}"
		LINK=""
		while read p; do
			if [[ ${p:0:1} != "#" ]]
			then
				L=$(curl -s $p/?action=install\&info=$(uname)-$(uname -r)-$(uname -p)\&package=$PACKAGE)
				if [[ ${L:0:4} == "http" ]]
				then
					LINK=$L
				fi
			fi
		done < /etc/khap.d/repos
		if [ "$LINK" != "" ]; then
			echo "Updating:	$PACKAGE"
			mkdir -p /etc/khap.d/temp
			rm -rf /etc/khap.d/temp/*
			curl -s $LINK --output /etc/khap.d/temp.tgz
			handle_versioning
			cp -r /etc/khap.d/temp/tree/* /usr/local/
		else
			echo "Error:	$PACKAGE not found"
		fi
	done < /etc/khap.d/versions
fi